"""new colum fee to trades

Revision ID: 4f9a02005057
Revises: beae3c70dfe0
Create Date: 2025-12-06 18:25:17.589109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9a02005057'
down_revision: Union[str, Sequence[str], None] = 'beae3c70dfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('fee', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'fee')
    # ### end Alembic commands ###
