"""del fee from asset_prices

Revision ID: 844012ff4b04
Revises: 4f9a02005057
Create Date: 2025-12-11 02:35:30.608396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844012ff4b04'
down_revision: Union[str, Sequence[str], None] = '4f9a02005057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('fee', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
