"""init

Revision ID: ad24cca96422
Revises: 
Create Date: 2025-11-27 22:07:51.415152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad24cca96422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('asset_prices_asset_timestamp_idx'), table_name='asset_prices')
    op.drop_index(op.f('asset_prices_timestamp_idx'), table_name='asset_prices')
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolio_positions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('portfolio_positions_portfolio_id_asset_id_key'), 'portfolio_positions', type_='unique')
    op.alter_column('portfolios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trades', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trades', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portfolios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('portfolio_positions_portfolio_id_asset_id_key'), 'portfolio_positions', ['portfolio_id', 'asset_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('portfolio_positions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('asset_prices_timestamp_idx'), 'asset_prices', ['timestamp'], unique=False)
    op.create_index(op.f('asset_prices_asset_timestamp_idx'), 'asset_prices', ['asset_id', sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
